### PR TITLE
Check your answers page

### PR DESCRIPTION
**Pull request by Davidslv**
Story: https://trello.com/c/eLQkrUGd/203-dc-work-on-check-your-answers-page

This is a close implementation of [this page in the prototype](https://moj-disclosure-checker.herokuapp.com/prototype-2/check-your-answers/check-your-answers)

Except it will have the buttons to add another sentence or another conviction until [this story is completed](https://trello.com/c/krAsstbg/204-dc-question-page-to-new-caution-conviction)

### After

image

### CODE REVIEW

**Comment by Davidslv** [comment]
[[DC] Work on Check Your Answers Page](https://trello.com/c/eLQkrUGd/203-dc-work-on-check-your-answers-page)

**Review by zheileman — COMMENTED** [review]
Let me have a think at the problem of the "caution/conviction type locales", but we probably need to change some things 👍

**Comment by Davidslv** [comment]
Will update the code according to the decision of todays meeting, I've commented on the card to reflect this https://trello.com/c/eLQkrUGd/203-dc-work-on-check-your-answers-page#comment-605876c00b3b3c0328f298f0

We don't want to break the results page for single convictions

**Comment by Davidslv** [comment]
Closing this PR to avoid confusion. Version 2 is the agreed version for this.

**Pull request closed without merging**
